name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Discord Push Notification
        uses: rjstone/discord-webhook-notify@v1
        if: matrix.node-version == '22.x'
        with:
          severity: info
          details: "🚀 มีการ Push โค้ดใหม่ กำลังเริ่มทดสอบ..."
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - run: npm ci
      - run: npm test

      - name: Discord Build Success Notification
        uses: rjstone/discord-webhook-notify@v1
        if: always() && matrix.node-version == '22.x'
        with:
          severity: ${{ job.status == 'success' && 'info' || 'error' }}
          details: "✅ Build ${{ job.status }}! พร้อมใช้งานครับ"
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Google Auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev

      - name: Build and Push Container
        run: |-
          docker build -t asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/my-app:${{ github.sha }} .
          docker push asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/my-app:${{ github.sha }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: "google-github-actions/deploy-cloudrun@v2"
        with:
          service: "my-node-app"
          image: "asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/my-app:${{ github.sha }}"
          region: "asia-southeast1"
          flags: "--allow-unauthenticated"

      - name: Discord Deploy Notification
        uses: rjstone/discord-webhook-notify@v1
        if: always()
        with:
          severity: ${{ job.status == 'success' && 'info' || 'error' }}
          details: "🚀 Deploy สำเร็จแล้ว! ดูผลงานได้ที่นี่: ${{ steps.deploy.outputs.url }}"
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
